from dataclasses import dataclass, field
from typing import Any


START = "START"
FINISH = "END"
BASE = "0"
RHOMB = "P"
BIG_RHOMB = "**P"
SQUARE = "K"
H_PATH = "-"
V_PATH = "|"
DOWN_RIGHT = ",-"
DOWN_LEFT = "-,"
UP_RIGHT = "'-"
UP_LEFT = "-'"
GO_LEFT = "->"
GO_RIGHT = "<-"
GO_UP = "_UP"
GO_DOWN = "_DOWN"
V_RIGHT = "|-"
V_LEFT = "-|"
H_UP = "-'-"
H_DOWN = "-,-"
CROSS = "+"
STAR = "*"

BOLD = "$"

@dataclass
class CellParams:
    params: dict[str, Any] = field(default_factory=dict)
    text_params: dict[str, Any] = field(default_factory=dict)

def tag_creator(
    tag: str,
    bold: bool = False,
    color: str | None = None,
    params: CellParams | None = None,
):
    def func(text: str) -> str:
        result = "_" + tag  + "_" + text
        # cell_params = CellParams() if params is None else params
        if bold:
            result = BOLD + result
        if color:
            result += "#" + color
        # if params is not None:
        #     result
        return result
    return func

def bold(text: str) -> str:
    return BOLD + text

star = tag_creator(STAR)
P = tag_creator(RHOMB)
BIG_P = tag_creator(BIG_RHOMB, bold=True, color="#FFD818")
K = tag_creator(SQUARE)
h_path = tag_creator(H_PATH)
v_path = tag_creator(V_PATH)

map = [
    [START, None, None          , ""        , ""            , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , ""      , ""        , ""            , ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [None , None, None          , GO_RIGHT  , "1"           , H_PATH  , "2"           , GO_RIGHT, "B1"          , GO_RIGHT, P("A##FF3333"), ""      , ""        , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , ""      , ""        , ""            , ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , FINISH         , None           , None    , ""   ],
    [None , None, None          , ""        , ""            , ""      , V_PATH        , ""      , ""            , ""      , ""            , ""      , ""        , ""      , P("H##00FFFF"), GO_LEFT, H_DOWN        , H_PATH, H_PATH    , H_PATH , "B9"          , ""      , ""        , ""            , ""        , ""            , "B10"         , H_PATH    , H_PATH    , H_PATH    , H_DOWN         , GO_RIGHT      , P("I##FF00FF") , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , None           , None           , None    , ""   ],
    [""   , ""  , ""            , ""        , ""            , ""      , V_PATH        , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , GO_DOWN       , ""    , ""        , ""     , GO_UP         , ""      , ""        , ""            , ""        , ""            , GO_UP         , ""        , ""        , ""        , V_PATH         , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , None           , None           , None    , ""   ],
    [""   , ""  , DOWN_RIGHT    , H_PATH    , "4"           , H_PATH  , "3"           , GO_LEFT , P("A##FF3333"), ""      , ""            , ""      , ""        , ""      , ""            , ""     , P("G##793D00"), ""    , DOWN_RIGHT, H_PATH , CROSS         , H_PATH  , DOWN_LEFT , ""            , DOWN_RIGHT, H_PATH        , CROSS         , H_PATH    , DOWN_LEFT , ""        , GO_DOWN        , ""            , ""             , ""            , ""            , ""            , DOWN_RIGHT, GO_RIGHT      , "B12"         , H_PATH        , "93"      , H_PATH    , "94"      , H_PATH   , "95"      , DOWN_LEFT, ""      , ""             , ""       , ""      , ""             , bold(GO_UP)    , ""      , ""   ],
    [""   , ""  , V_PATH        , ""        , ""            , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , V_PATH    , ""     , V_PATH        , ""      , V_PATH    , ""            , V_PATH    , ""            , V_PATH        , ""        , V_PATH    , ""        , P("G##793D00") , ""            , ""             , ""            , ""            , ""            , V_PATH    , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , V_PATH   , ""      , ""             , ""       , ""      , ""             , bold(V_PATH)   , ""      , ""   ],
    [""   , ""  , "5"           , ""        , "8"           , H_PATH  , "9"           , ""      , P("C##3333FF"), GO_RIGHT, "13#green"    , GO_RIGHT, "14#green", GO_RIGHT, "15#green"    , H_PATH , DOWN_LEFT     , ""    , "81#red"  , ""     , "82#red"      , ""      , "83#red"  , ""            , "84#red"  , ""            , "85#red"      , ""        , "86#red"  , ""        , ""             , ""            , ""             , P("K##FF8000"), ""            , ""            , V_RIGHT   , GO_RIGHT      , "B13"         , H_PATH        , "93#green", H_PATH    , "94#green", H_PATH   , "95#green", V_LEFT   , ""      , ""             , ""       , ""      , ""             , bold(V_PATH)   , ""      , ""   ],
    [""   , ""  , V_PATH        , ""        , V_PATH        , ""      , V_PATH        , ""      , ""            , ""      , V_PATH        , ""      , ""        , ""      , ""            , ""     , V_PATH        , ""    , V_PATH    , ""     , V_PATH        , ""      , V_PATH    , ""            , V_PATH    , ""            , V_PATH        , ""        , V_PATH    , ""        , BIG_P("\u2605"), None          , ""             , GO_DOWN       , ""            , ""            , V_PATH    , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , V_PATH   , ""      , ""             , ""       , ""      , star("100")    , None           , None    , ""   ],
    [""   , ""  , "6"           , H_PATH    , "7"           , ""      , "10"          , H_PATH  , "11"          , H_PATH  , "12"          , GO_RIGHT, "13"      , GO_RIGHT, "14"          , ""     , V_PATH        , ""    , "81#green", ""     , "82#green"    , ""      , "83#green", ""            , "84#green", ""            , "85#green"    , ""        , "86#green", ""        , None           , None          , GO_RIGHT       , "92"          , H_PATH        , K("4")        , V_LEFT    , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , V_RIGHT  , GO_RIGHT, "99"           , H_PATH   , GO_RIGHT, None           , None           , None    , ""   ],
    [""   , ""  , ""            , ""        , ""            , ""      , GO_DOWN       , ""      , ""            , ""      , ""            , ""      , ""        , ""      , V_PATH        , ""     , GO_DOWN       , ""    , V_PATH    , ""     , V_PATH        , ""      , V_PATH    , ""            , V_PATH    , ""            , V_PATH        , ""        , V_PATH    , ""        , None           , None          , ""             , ""            , ""            , ""            , V_PATH    , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , V_PATH   , ""      , GO_DOWN        , ""       , ""      , None           , None           , None    , ""   ],
    [""   , ""  , P("B##00FF00"), ""        , ""            , ""      , P("B##00FF00"), ""      , ""            , ""      , ""            , ""      , ""        , ""      , "15"          , H_PATH , "16"          , ""    , "81"      , ""     , "82"          , ""      , "83"      , ""            , "84"      , ""            , "85"          , ""        , "86"      , ""        , ""             , ""            , ""             , ""            , ""            , ""            , V_RIGHT   , GO_RIGHT      , "B14"         , H_PATH        , "96"      , H_PATH    , "97"      , H_PATH   , "98"      , V_LEFT   , ""      , P("K##FF8000") , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , GO_DOWN       , ""        , ""            , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , V_PATH        , ""    , GO_UP     , ""     , GO_UP         , ""      , GO_UP     , ""            , GO_UP     , ""            , GO_UP         , ""        , GO_UP     , ""        , ""             , ""            , ""             , ""            , ""            , ""            , V_PATH    , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , V_PATH   , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , "B2"          , GO_RIGHT  , P("C##3333FF"), ""      , ""            , ""      , "18"          , H_PATH  , "17"          , H_PATH  , H_PATH    , H_PATH  , H_PATH        , H_PATH , UP_LEFT       , ""    , UP_RIGHT  , H_PATH , H_UP          , H_PATH  , H_UP      , H_DOWN        , H_UP      , H_PATH        , H_UP          , H_PATH    , UP_LEFT   , ""        , ""             , ""            , ""             , ""            , ""            , ""            , UP_RIGHT  , GO_RIGHT      , "B15"         , H_PATH        , "96#green", H_PATH    , "97#green", H_PATH   , "98#green", UP_LEFT  , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , ""            , ""        , ""            , ""      , ""            , ""      , V_PATH        , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , ""      , ""        , V_PATH        , ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , "22"          , H_PATH    , "21"          , H_PATH  , "20"          , H_PATH  , "19"          , H_PATH  , "20#green"    , GO_RIGHT, "21#green", ""      , ""            , ""     , ""            , ""    , ""        , ""     , P("G##793D00"), H_PATH  , GO_RIGHT  , "80"          , GO_LEFT   , H_PATH        , P("J##00C3FF"), ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , V_PATH        , ""        , ""            , ""      , ""            , ""      , GO_UP         , ""      , ""            , ""      , V_PATH    , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , ""      , ""        , V_PATH        , ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , "23"          , ""        , ""            , ""      , ""            , ""      , V_PATH        , ""      , ""            , ""      , "22#green", ""      , ""            , ""     , ""            , ""    , DOWN_RIGHT, H_PATH , H_PATH        , H_PATH  , H_PATH    , K("3")        , H_PATH    , H_PATH        , H_PATH        , H_PATH    , H_PATH    , DOWN_LEFT , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , V_PATH        , ""        , ""            , ""      , ""            , ""      , V_PATH        , ""      , ""            , ""      , V_PATH    , ""      , ""            , ""     , ""            , ""    , V_PATH    , ""     , ""            , ""      , ""        , GO_UP         , ""        , ""            , ""            , ""        , ""        , V_PATH    , ""             , ""            , ""             , ""            , ""            , ""            , ""        , P("J##00C3FF"), ""            , DOWN_RIGHT    , GO_RIGHT  , "?#green" , H_PATH    , DOWN_LEFT, ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , "24"          , GO_LEFT   , H_PATH        , K("1")  , GO_LEFT       , GO_RIGHT, "23#green"    , H_PATH  , H_PATH        , H_PATH  , UP_LEFT   , ""      , ""            , ""     , ""            , ""    , "79"      , H_PATH , GO_RIGHT      , "B7"    , H_PATH    , H_UP          , H_PATH    , "B8"          , GO_LEFT       , "75#green", GO_LEFT   , "74#green", ""             , ""            , ""             , P("H##00FFFF"), H_PATH        , DOWN_LEFT     , ""        , GO_UP         , ""            , V_PATH        , ""        , ""        , ""        , GO_DOWN  , ""        , ""       , ""      , ""             , ""       , ""      , ""             , BIG_P("\u2605"), None    , ""   ],
    [""   , ""  , V_PATH        , ""        , ""            , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , V_PATH    , ""     , ""            , GO_UP   , ""        , ""            , ""        , GO_UP         , ""            , ""        , ""        , V_PATH    , ""             , ""            , ""             , ""            , ""            , V_RIGHT       , GO_RIGHT  , "87"          , H_PATH        , "88"          , H_PATH    , H_PATH    , H_PATH    , "89"     , H_PATH    , "B11"    , H_PATH  , "90"           , H_PATH   , "91"    , GO_RIGHT       , None           , None    , ""   ],
    [""   , ""  , "25"          , H_PATH    , "26"          , H_PATH  , "27"          , H_PATH  , "28"          , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , "78"      , ""     , ""            , UP_RIGHT, H_PATH    , H_DOWN        , H_PATH    , UP_LEFT       , ""            , ""        , ""        , V_PATH    , ""             , ""            , ""             , P("I##FF00FF"), H_PATH        , UP_LEFT       , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , None           , None    , ""   ],
    [""   , ""  , GO_UP         , ""        , ""            , ""      , ""            , ""      , V_PATH        , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , V_PATH    , ""     , ""            , ""      , ""        , V_PATH        , ""        , ""            , ""            , ""        , ""        , "73#green", ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , UP_RIGHT      , H_PATH    , "29"          , H_PATH  , H_PATH        , H_PATH  , UP_LEFT       , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , "77"      , ""     , ""            , ""      , ""        , "B6"          , ""        , ""            , ""            , ""        , ""        , V_PATH    , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , ""            , ""        , V_PATH        , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , V_PATH    , ""     , ""            , ""      , ""        , GO_UP         , ""        , ""            , ""            , ""        , ""        , "72#green", H_PATH         , "71#green"    , H_PATH         , "70#green"    , H_PATH        , "69#green"    , H_PATH    , "68#green"    , H_PATH        , "67#green"    , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , ""            , ""        , V_RIGHT       , H_PATH  , GO_RIGHT      , "30"    , ""            , ""      , ""            , ""      , DOWN_RIGHT, H_PATH  , "35#green"    , ""     , ""            , ""    , "76"      , ""     , ""            , ""      , ""        , P("F##B950FF"), ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , V_PATH        , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , ""            , ""        , V_PATH        , ""      , ""            , GO_DOWN , ""            , ""      , ""            , ""      , V_PATH    , ""      , GO_DOWN       , ""     , ""            , ""    , V_PATH    , ""     , ""            , ""      , ""        , ""            , ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , V_PATH        , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , ""            , ""        , V_RIGHT       , H_PATH  , GO_RIGHT      , "31"    , ""            , ""      , ""            , ""      , V_RIGHT   , H_PATH  , "35"          , H_PATH , DOWN_LEFT     , ""    , "75"      , GO_LEFT, H_PATH        , "74"    , GO_LEFT   , "73"          , GO_LEFT   , "72"          , GO_LEFT       , "71"      , GO_LEFT   , "70"      , GO_LEFT        , "69"          , GO_LEFT        , H_PATH        , "68"          , H_PATH        , "67"      , H_PATH        , H_PATH        , "66"          , H_PATH    , H_DOWN    , H_PATH    , "65"     , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , ""            , ""        , V_PATH        , ""      , ""            , GO_DOWN , ""            , ""      , ""            , ""      , V_PATH    , ""      , GO_UP         , ""     , V_PATH        , ""    , ""        , ""     , ""            , ""      , ""        , ""            , ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , GO_DOWN       , ""        , V_PATH    , ""        , GO_UP    , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , ""            , ""        , UP_RIGHT      , H_PATH  , H_PATH        , "32"    , ""            , ""      , ""            , ""      , V_RIGHT   , H_PATH  , "35#red"      , ""     , V_PATH        , ""    , ""        , ""     , ""            , ""      , K("2")    , H_PATH        , H_DOWN    , H_PATH        , P("D##B2FF00"), ""        , "39#green", H_PATH    , H_PATH         , "40#green"    , GO_RIGHT       , "41#green"    , H_PATH        , "42#green"    , H_PATH    , "43#green"    , ""            , P("F##B950FF"), ""        , V_PATH    , ""        , "64"     , GO_LEFT   , "63"     , GO_LEFT , "62"           , GO_LEFT  , "61"    , GO_LEFT        , "60"           , GO_LEFT , "59" ],
    [""   , ""  , ""            , ""        , ""            , ""      , ""            , V_PATH  , ""            , ""      , ""            , ""      , V_PATH    , ""      , ""            , ""     , V_PATH        , ""    , ""        , ""     , ""            , ""      , GO_UP     , ""            , GO_DOWN   , ""            , ""            , ""        , V_PATH    , ""        , ""             , GO_DOWN       , ""             , ""            , ""            , ""            , ""        , GO_DOWN       , ""            , ""            , ""        , V_PATH    , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , GO_UP],
    [""   , ""  , "B3"          , GO_LEFT   , H_PATH        , H_PATH  , H_PATH        , "33"    , ""            , ""      , ""            , ""      , V_PATH    , ""      , ""            , ""     , UP_RIGHT      , H_PATH, "$x"      , H_PATH , H_PATH        , H_PATH  , "36"      , H_PATH        , "37"      , H_PATH        , H_PATH        , H_PATH    , "38"      , H_PATH    , H_PATH         , "39"          , GO_LEFT        , "$?"          , GO_LEFT       , P("E##FF0090"), ""        , "43"          , H_PATH        , "44"          , ""        , V_PATH    , ""        , ""       , ""        , ""       , ""      , "55"           , GO_RIGHT , "56"    , GO_RIGHT       , "57"           , GO_RIGHT, "58" ],
    [""   , ""  , V_PATH        , ""        , ""            , ""      , ""            , V_PATH  , ""            , ""      , ""            , ""      , V_PATH    , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , ""      , ""        , ""            , V_PATH    , ""            , ""            , ""        , GO_DOWN   , ""        , ""             , V_PATH        , ""             , ""            , ""            , ""            , ""        , V_PATH        , ""            , V_PATH        , ""        , V_PATH    , ""        , ""       , ""        , ""       , ""      , GO_UP          , ""       , ""      , ""             , ""             , ""      , ""   ],
    [""   , ""  , UP_RIGHT      , "34#green", H_PATH        , "34#red", GO_RIGHT      , "34"    , H_PATH        , H_PATH  , H_PATH        , H_PATH  , UP_LEFT   , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , "B4"    , GO_LEFT   , H_PATH        , UP_LEFT   , ""            , ""            , ""        , "B5"      , ""        , ""             , "40"          , H_PATH         , "41"          , H_PATH        , "42"          , H_PATH    , UP_LEFT       , ""            , V_PATH        , ""        , V_PATH    , ""        , ""       , ""        , ""       , ""      , "54"           , GO_LEFT  , "53"    , GO_LEFT        , "52"           , GO_LEFT , "51" ],
    [""   , ""  , ""            , ""        , ""            , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , V_PATH  , ""        , ""            , ""        , ""            , ""            , ""        , V_PATH    , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , V_PATH        , ""        , GO_DOWN   , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , GO_UP],
    [""   , ""  , ""            , ""        , ""            , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , UP_RIGHT, H_PATH    , H_PATH        , GO_RIGHT  , P("D##B2FF00"), ""            , ""        , UP_RIGHT  , H_PATH    , P("E##FF0090") , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , "45"          , ""        , "46"      , H_PATH    , H_PATH   , H_PATH    , H_PATH   , GO_RIGHT, "47"           , GO_RIGHT , "48"    , GO_RIGHT       , "49"           , GO_RIGHT, "50" ],
    [""   , ""  , ""            , ""        , ""            , ""      , ""            , ""      , ""            , ""      , ""            , ""      , ""        , ""      , ""            , ""     , ""            , ""    , ""        , ""     , ""            , ""      , ""        , ""            , ""        , ""            , ""            , ""        , ""        , ""        , ""             , ""            , ""             , ""            , ""            , ""            , ""        , ""            , ""            , ""            , ""        , ""        , ""        , ""       , ""        , ""       , ""      , ""             , ""       , ""      , ""             , ""             , ""      , ""   ],
]