from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Literal


class MapTag(str, Enum):
    START = "START"
    FINISH = "END"
    BASE = "BASE"
    RHOMB = "RHOMB"
    BIG_RHOMB = "BIG_RHOMB"
    SQUARE = "SQUARE"
    H_PATH = "H_PATH"
    V_PATH = "V_PATH"
    DOWN_RIGHT = "DOWN_RIGHT"
    DOWN_LEFT = "DOWN_LEFT"
    UP_RIGHT = "UP_RIGHT"
    UP_LEFT = "UP_LEFT"
    GO_LEFT = "GO_LEFT"
    GO_RIGHT = "GO_RIGHT"
    GO_UP = "GO_UP"
    GO_DOWN = "GO_DOWN"
    V_RIGHT = "V_RIGHT"
    V_LEFT = "V_LEFT"
    H_UP = "H_UP"
    H_DOWN = "H_DOWN"
    CROSS = "CROSS"
    STAR = "STAR"
    CROSSED_H_PATH = "CROSSED_H_PATH"
    CROSSED_V_PATH = "CROSSED_V_PATH"


class MapState(str, Enum):
    NOT_VISITED = "NOT_VISITED"
    VISITED = "VISITED"
    CURRENT = "CURRENT"


@dataclass
class TextParams:
    text: str
    boxed: bool = False
    arrowed: Literal["l", "r"] | None = None
    extra_params: dict[str, Any] = field(default_factory=dict)


@dataclass
class CaptionInfo:
    contents: list[TextParams]
    relative_pos: Literal["left", "right", "up", "down", "center"] = "center"

    def copy(self) -> CaptionInfo:
        return CaptionInfo(
            contents=self.contents.copy(),
            relative_pos=self.relative_pos,
        )
    
    def __add__(self, other: CaptionInfo) -> CaptionInfo:
        new_contents = self.contents.copy()
        new_contents.extend(other.contents)
        return CaptionInfo(
            contents=new_contents,
            relative_pos=self.relative_pos,
        )

    def concatenate(self, other: CaptionInfo) -> None:
        self.contents.extend(other.contents)


@dataclass
class MapObjectInfo:
    tag: MapTag
    state: MapState = MapState.NOT_VISITED
    bold: bool = False
    color: str | None = None
    extra_params: dict[str, Any] = field(default_factory=dict)
    caption: list[TextParams] | None = None

    def copy(self) -> MapObjectInfo:
        return MapObjectInfo(
            tag=self.tag,
            state=self.state,
            bold=self.bold,
            color=self.color,
            extra_params=self.extra_params.copy(),
            caption=None if self.caption is None else self.caption.copy(),
        )

    def __add__(self, other: MapObjectInfo) -> MapObjectInfo:
        if self.tag != other.tag:
            raise ValueError("MapObjectInfo objects related to different tags cannot be summed")
        new_params = self.extra_params.copy()
        new_params.update(other.extra_params)
        if self.caption is None:
            if other.caption is not None:
                new_caption = other.caption.copy()
            else:
                new_caption = None
        elif other.caption is None:
            new_caption = self.caption.copy()
        else:
            new_caption = self.caption + other.caption
        return MapObjectInfo(
            tag=self.tag,
            state=self.state,
            bold=self.bold | other.bold,
            color=self.color or other.color,
            extra_params=new_params,
            caption=new_caption,
        )
    
    def __call__(
        self,
        text: str | list[str | TextParams], 
        boxed: bool = False,
        arrowed: Literal["l", "r"] | None = None,
    ) -> MapObjectInfo:
        if isinstance(text, str):
            contents = [
                TextParams(
                    text=text,
                    boxed=boxed,
                    arrowed=arrowed,
                ),
            ]
        else:
            contents = []
            for part in text:
                if isinstance(part, str):
                    contents.append(
                        TextParams(
                            text=part,
                            boxed=boxed,
                            arrowed=arrowed,
                        ),
                    )
                else:
                    contents.append(part)
        new_object = self.copy()
        if new_object.caption is None:
            new_object.caption = contents
        else:
            new_object.caption.extend(contents)
        return new_object


def bold(obj: MapObjectInfo) -> MapObjectInfo:
    return obj + MapObjectInfo(
        tag=obj.tag,
        bold=True,
    )

def color(obj: MapObjectInfo, color: str) -> MapObjectInfo:
    return obj + MapObjectInfo(
        tag=obj.tag,
        color=color,
    )

star = MapObjectInfo(MapTag.STAR)
P = MapObjectInfo(MapTag.RHOMB)
big_P = MapObjectInfo(MapTag.BIG_RHOMB, bold=True, color="#FFD818")
K = MapObjectInfo(MapTag.SQUARE, bold=True)
h_path = MapObjectInfo(MapTag.H_PATH)
v_path = MapObjectInfo(MapTag.V_PATH)
start = MapObjectInfo(MapTag.START, state=MapState.CURRENT)
finish = MapObjectInfo(MapTag.FINISH)
go_right = MapObjectInfo(MapTag.GO_RIGHT)
go_left = MapObjectInfo(MapTag.GO_LEFT)
go_up = MapObjectInfo(MapTag.GO_UP)
go_down = MapObjectInfo(MapTag.GO_DOWN)
h_up = MapObjectInfo(MapTag.H_UP)
h_down = MapObjectInfo(MapTag.H_DOWN)
v_left = MapObjectInfo(MapTag.V_LEFT)
v_right = MapObjectInfo(MapTag.V_RIGHT)
cross = MapObjectInfo(MapTag.CROSS)
down_left = MapObjectInfo(MapTag.DOWN_LEFT)
down_right = MapObjectInfo(MapTag.DOWN_RIGHT)
up_left = MapObjectInfo(MapTag.UP_LEFT)
up_right = MapObjectInfo(MapTag.UP_RIGHT)
base = MapObjectInfo(MapTag.BASE)
crossed_h_path = MapObjectInfo(MapTag.CROSSED_H_PATH)
crossed_v_path = MapObjectInfo(MapTag.CROSSED_V_PATH)

initial_map: list[list[Literal[""] | None | MapObjectInfo]] = [
    [start("START"), None, None                      , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , ""        , ""                                  , ""                        , ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [None          , None, None                      , go_right                  , base("1")                 , h_path                                 , base("2")                                    , h_path([TextParams("6-12", boxed=True), " 1"]) , go_right                  , base("B1")                                 , go_right                  , color(P("A"), "#FF3333"), ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , ""        , ""                                  , ""                        , ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , finish("END")  , None             , None    , ""        ],
    [None          , None, None                      , ""                        , ""                        , ""                                     , v_path([TextParams("2-5", boxed=True), " 1"]), ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , color(P("H"), "#00FFFF"), go_left("B"), h_down                    , h_path, h_path                              , h_path , base("B9")                                    , ""        , ""                                  , ""                        , ""                                  , ""                        , base("B10")                           , h_path                    , h_path                                          , h_path                                        , h_down                     , go_right("B")                 , color(P("I"), "#FF00FF") , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , None           , None             , None    , ""        ],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , v_path                                       , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , go_down("R")              , ""    , ""                                  , ""     , go_up("1")                                    , ""        , ""                                  , ""                        , ""                                  , ""                        , go_up("1")                            , ""                        , ""                                              , ""                                            , v_path("R")                , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , None           , None             , None    , ""        ],
    [""            , ""  , down_right                , h_path("6")               , base("4")                 , h_path("2")                            , base("3")                                    , go_left                                        , color(P("A"), "#FF3333"), ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , color(P("G"), "#793D00"), ""    , down_right                          , h_path , cross                                         , h_path    , down_left                           , ""                        , down_right                          , h_path                    , cross                                 , h_path                    , down_left                                       , ""                                            , go_down                    , ""                            , ""                         , ""                        , ""            , ""                        , down_right , go_right                  , base("B12")                            , h_path                                            , base("93")                                      , h_path("1")                                       , base("94")                , h_path("2")   , base("95")                , down_left  , ""      , ""                         , ""         , ""        , ""             , bold(go_up)      , ""      , ""        ],
    [""            , ""  , v_path                    , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , v_path                              , ""     , v_path                                        , ""        , v_path                              , ""                        , v_path                              , ""                        , v_path                                , ""                        , v_path                                          , ""                                            , color(P("G"), "#793D00") , ""                            , ""                         , ""                        , ""            , ""                        , v_path     , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , v_path     , ""      , ""                         , ""         , ""        , ""             , bold(v_path)("6"), ""      , ""        ],
    [""            , ""  , base("5")                 , ""                        , base("8")                 , h_path("3")                            , base("9")                                    , ""                                             , color(P("C"), "#3333FF"), go_right                                   , color(base("13"), "green"), go_right("4")             , color(base("14"), "green")                     , go_right("3")                                  , color(base("15"), "green"), h_path      , down_left                 , ""    , color(base("81"), "red")            , ""     , color(base("82"), "red")                      , ""        , color(base("83"), "red")            , ""                        , color(base("84"), "red")            , ""                        , color(base("85"), "red")              , ""                        , color(base("86"), "red")                        , ""                                            , ""                         , ""                            , ""                         , color(P("K"), "#FF8000"), ""            , ""                        , v_right    , go_right                  , base("B13")                            , h_path                                            , color(base("93"), "green")                      , h_path("2")                                       , color(base("94"), "green"), h_path("3")   , color(base("95"), "green"), v_left     , ""      , ""                         , ""         , ""        , ""             , bold(v_path)     , ""      , ""        ],
    [""            , ""  , v_path("3")               , ""                        , v_path("3")               , ""                                     , v_path("3")                                  , ""                                             , ""                        , ""                                         , v_path("5")               , ""                        , ""                                             , ""                                             , ""                        , ""          , v_path                    , ""    , v_path("2")                         , ""     , v_path("2")                                   , ""        , v_path("2")                         , ""                        , v_path("2")                         , ""                        , v_path("2")                           , ""                        , v_path("2")                                     , ""                                            , big_P("\u2605")            , None                          , ""                         , go_down                   , ""            , ""                        , v_path     , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , v_path     , ""      , ""                         , ""         , ""        , star("100")    , None             , None    , ""        ],
    [""            , ""  , base("6")                 , h_path("3")               , base("7")                 , ""                                     , base("10")                                   , h_path("1B")                                   , base("11")                , h_path("5")                                , base("12")                , h_path("4")               , base("13")                                     , h_path("3")                                    , base("14")                , ""          , v_path("1")               , ""    , color(base("81"), "green")          , ""     , color(base("82"), "green")                    , ""        , color(base("83"), "green")          , ""                        , color(base("84"), "green")          , ""                        , color(base("85"), "green")            , ""                        , color(base("86"), "green")                      , ""                                            , None                       , None                          , go_right                   , base("92")                , h_path("1")   , K("4")                    , v_left     , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , v_right    , go_right, base("99")                 , h_path("1"), go_right  , None           , None             , None    , ""        ],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , go_down("1R")                                , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , v_path("2")               , ""          , go_down                   , ""    , v_path                              , ""     , v_path                                        , ""        , v_path                              , ""                        , v_path                              , ""                        , v_path                                , ""                        , v_path                                          , ""                                            , None                       , None                          , ""                         , v_path                    , ""            , ""                        , v_path     , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , v_path     , ""      , go_down                    , ""         , ""        , None           , None             , None    , ""        ],
    [""            , ""  , color(P("B"), "#00FF00"), ""                        , ""                        , ""                                     , color(P("B"), "#00FF00")                   , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , base("15")                , h_path      , base("16")                , ""    , base("81")                          , ""     , base("82")                                    , ""        , base("83")                          , ""                        , base("84")                          , ""                        , base("85")                            , ""                        , base("86")                                      , ""                                            , ""                         , ""                            , ""                         , color(base("x"), "green") , ""            , ""                        , v_right    , go_right                  , base("B14")                            , h_path                                            , base("96")                                      , h_path("3")                                       , base("97")                , h_path("4")   , base("98")                , v_left     , ""      , color(P("K"), "#FF8000") , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , go_down                   , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , v_path                    , ""    , go_up([TextParams("1", boxed=True)]), ""     , go_up([TextParams("2", boxed=True)])          , ""        , go_up([TextParams("3", boxed=True)]), ""                        , go_up([TextParams("4", boxed=True)]), ""                        , go_up([TextParams("5", boxed=True)])  , ""                        , go_up([TextParams("6", boxed=True)])            , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , v_path     , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , v_path     , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , base("B2")                , go_right                  , color(P("C"), "#3333FF"), ""                                     , ""                                           , ""                                             , base("18")                , h_path                                     , base("17")                , h_path                    , h_path                                         , h_path                                         , h_path                    , h_path      , up_left                   , ""    , up_right                            , h_path , h_up                                          , h_path    , h_up                                , h_down                    , h_up                                , h_path                    , h_up                                  , h_path                    , up_left                                         , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , up_right   , go_right                  , base("B15")                            , h_path                                            , color(base("96"), "green")                      , h_path("4")                                       , color(base("97"), "green"), h_path("5")   , color(base("98"), "green"), up_left    , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , ""                                           , ""                                             , v_path("4")               , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , ""        , ""                                  , v_path("4")               , ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , base("22")                , h_path                    , base("21")                , h_path                                 , base("20")                                   , h_path("2B")                                   , base("19")                , h_path(["R", TextParams("3", arrowed="l")]), color(base("20"), "green"), go_right                  , color(base("21"), "green")                     , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , color(P("G"), "#793D00")                    , h_path    , go_right                            , base("80")                , go_left                             , h_path                    , color(P("J"), "#00C3FF")            , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , v_path("6")               , ""                        , ""                        , ""                                     , ""                                           , ""                                             , go_up                     , ""                                         , ""                        , ""                        , v_path                                         , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , ""        , ""                                  , v_path("1")               , ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , base("23")                , ""                        , ""                        , ""                                     , ""                                           , ""                                             , v_path("1")               , ""                                         , ""                        , ""                        , color(base("22"), "green")                     , ""                                             , ""                        , ""          , ""                        , ""    , down_right                          , h_path , h_path([TextParams("3-11", boxed=True), " 2"]), h_path    , h_path                              , K("3")                    , h_path                              , h_path                    , h_path                                , h_path                    , h_path                                          , down_left                                     , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , v_path                    , ""                        , ""                        , ""                                     , ""                                           , ""                                             , v_path                    , ""                                         , ""                        , ""                        , v_path                                         , ""                                             , ""                        , ""          , ""                        , ""    , v_path                              , ""     , ""                                            , ""        , ""                                  , go_up                     , ""                                  , ""                        , ""                                    , ""                        , ""                                              , v_path                                        , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , color(P("J"), "#00C3FF"), ""                                     , down_right([TextParams("8-12", boxed=True), " 1"]), go_right                                        , color(base("?"), "green")                         , h_path                    , down_left     , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , base("24")                , go_left                   , h_path("1R")              , K("1")                                 , go_left(["2", TextParams("B", arrowed="r")]) , go_right                                       , color(base("23"), "green"), h_path                                     , h_path("6")               , h_path                    , up_left                                        , ""                                             , ""                        , ""          , ""                        , ""    , base("79")                          , h_path , go_right([TextParams("2,12", boxed=True)])    , base("B7"), h_path                              , h_up("1")                 , h_path                              , base("B8")                , go_left                               , color(base("75"), "green"), go_left([TextParams("2,12", boxed=True)])       , color(base("74"), "green")                    , ""                         , ""                            , ""                         , color(P("H"), "#00FFFF"), h_path        , down_left                 , ""         , go_up                     , ""                                     , v_path                                            , ""                                              , ""                                                , ""                        , go_down       , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , big_P("\u2605")  , None    , ""        ],
    [""            , ""  , v_path                    , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , v_path("3")                         , ""     , ""                                            , go_up     , ""                                  , ""                        , ""                                  , go_up                     , ""                                    , ""                        , ""                                              , v_path                                        , ""                         , ""                            , ""                         , ""                        , ""            , v_right                   , go_right   , base("87")                , h_path("2")                            , base("88")                                        , h_path                                          , h_path([TextParams("2-7,9-11", boxed=True), " 3"]), h_path                    , base("89")    , h_path("4")               , base("B11"), h_path  , base("90")                 , h_path("1"), base("91"), go_right       , None             , None    , ""        ],
    [""            , ""  , base("25")                , h_path("3")               , base("26")                , h_path                                 , base("27")                                   , h_path                                         , base("28")                , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , base("78")                          , ""     , ""                                            , up_right  , h_path("1B")                        , h_down                    , h_path("1R")                        , up_left                   , ""                                    , ""                        , ""                                              , v_path                                        , ""                         , ""                            , ""                         , color(P("I"), "#FF00FF"), h_path        , up_left                   , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , None             , None    , ""        ],
    [""            , ""  , go_up                     , ""                        , ""                        , ""                                     , ""                                           , ""                                             , v_path                    , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , v_path("6")                         , ""     , ""                                            , ""        , ""                                  , v_path                    , ""                                  , ""                        , ""                                    , ""                        , ""                                              , color(base("73"), "green")                    , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , up_right                  , h_path                    , base("29")                , h_path                                 , h_path("2")                                  , h_path                                         , up_left                   , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , base("77")                          , ""     , ""                                            , ""        , ""                                  , base("B6")                , ""                                  , ""                        , ""                                    , ""                        , ""                                              , v_path("6")                                   , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , v_path                    , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , v_path("6")                         , ""     , ""                                            , ""        , ""                                  , go_up                     , ""                                  , ""                        , ""                                    , ""                        , ""                                              , color(base("72"), "green")                    , h_path("5")                , color(base("71"), "green")    , h_path("4")                , color(base("70"), "green"), h_path("3")   , color(base("69"), "green"), h_path("2"), color(base("68"), "green"), h_path("1")                            , color(base("67"), "green")                        , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , v_right                   , h_path([TextParams("1-2", boxed=True)]), go_right                                     , base("30")                                     , ""                        , ""                                         , ""                        , down_right                , h_path([TextParams("2-5", boxed=True), " 1"])  , h_path                                         , color(base("35"), "green"), ""          , ""                        , ""    , base("76")                          , ""     , ""                                            , ""        , ""                                  , color(P("F"), "#B950FF"), ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , v_path([TextParams("6-10", boxed=True)])          , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , v_path                    , ""                                     , ""                                           , go_down                                        , ""                        , ""                                         , ""                        , v_path                    , ""                                             , ""                                             , go_down                   , ""          , ""                        , ""    , v_path("4")                         , ""     , ""                                            , ""        , ""                                  , ""                        , ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , v_path                                            , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , v_right                   , h_path([TextParams("3-4", boxed=True)]), go_right                                     , base("31")                                     , ""                        , ""                                         , ""                        , v_right                   , h_path([TextParams("6-9", boxed=True), " 2"])  , h_path                                         , base("35")                , h_path      , down_left                 , ""    , base("75")                          , go_left, crossed_h_path                                , base("74"), go_left                             , base("73")                , go_left                             , base("72")                , go_left                               , base("71")                , go_left                                         , base("70")                                    , go_left                    , base("69")                    , go_left                    , crossed_h_path            , base("68")    , h_path("3")               , base("67") , h_path                    , h_path([TextParams("2-5", boxed=True)]), base("66")                                        , h_path("1")                                     , h_down                                            , h_path                    , base("65")    , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , v_path                    , ""                                     , ""                                           , go_down                                        , ""                        , ""                                         , ""                        , v_path                    , ""                                             , ""                                             , go_up                     , ""          , v_path                    , ""    , ""                                  , ""     , ""                                            , ""        , ""                                  , ""                        , ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , go_down([TextParams("11-12", boxed=True)])        , ""                                              , v_path                                            , ""                        , go_up         , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , up_right                  , h_path([TextParams("5-6", boxed=True)]), h_path([TextParams("2", arrowed="l")])       , base("32")                                     , ""                        , ""                                         , ""                        , v_right                   , h_path([TextParams("10-12", boxed=True), " 3"]), h_path                                         , color(base("35"), "red")  , ""          , v_path                    , ""    , ""                                  , ""     , ""                                            , ""        , K("2")                              , h_path                    , h_down                              , h_path                    , color(P("D"), "#B2FF00")            , ""                        , color(base("39"), "green")                      , h_path                                        , h_path                     , color(base("40"), "green")    , go_right("2R")             , color(base("41"), "green"), h_path("3")   , color(base("42"), "green"), h_path("1"), color(base("43"), "green"), ""                                     , color(P("F"), "#B950FF")                        , ""                                              , v_path                                            , ""                        , crossed_v_path, ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , ""                                           , v_path                                         , ""                        , ""                                         , ""                        , v_path                    , ""                                             , ""                                             , ""                        , ""          , v_path                    , ""    , ""                                  , ""     , ""                                            , ""        , go_up                               , ""                        , v_path("3")                         , ""                        , ""                                    , ""                        , v_path([TextParams("2-5", boxed=True), " 6"])   , ""                                            , ""                         , v_path("2B")                  , ""                         , ""                        , ""            , ""                        , ""         , v_path                    , ""                                     , ""                                                , ""                                              , v_path("2")                                       , ""                        , base("64")    , go_left                   , base("63") , go_left , base("62")                 , go_left    , base("61"), go_left        , base("60")       , go_left , base("59")],
    [""            , ""  , base("B3")                , go_left                   , h_path                    , h_path("1,1")                          , h_path                                       , base("33")                                     , ""                        , ""                                         , ""                        , v_path                    , ""                                             , ""                                             , ""                        , ""          , v_path                    , ""    , ""                                  , ""     , ""                                            , ""        , v_path                              , ""                        , go_down                             , ""                        , ""                                    , ""                        , v_path                                          , ""                                            , ""                         , go_down                       , ""                         , ""                        , ""            , ""                        , ""         , go_down                   , ""                                     , ""                                                , ""                                              , v_path                                            , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , go_up     ],
    [""            , ""  , v_path                    , ""                        , ""                        , ""                                     , ""                                           , v_path                                         , ""                        , ""                                         , ""                        , v_path                    , ""                                             , ""                                             , ""                        , ""          , up_right                  , h_path, bold(base("x"))                     , h_path , h_path("1")                                   , h_path    , base("36")                          , h_path                    , base("37")                          , h_path("4B")              , h_path([TextParams("3", arrowed="l")]), h_path                    , base("38")                                      , h_path([TextParams("6-10", boxed=True), " 6"]), h_path                     , base("39")                    , go_left                    , bold(base("?"))           , go_left("2")  , color(P("E"), "#FF0090"), ""         , base("43")                , h_path("4")                            , base("44")                                        , ""                                              , v_path                                            , ""                        , ""            , ""                        , ""         , ""      , base("55")                 , go_right   , base("56"), go_right       , base("57")       , go_right, base("58")],
    [""            , ""  , up_right                  , color(base("34"), "green"), h_path                    , color(base("34"), "red")               , go_right("4")                                , base("34")                                     , h_path                    , h_path                                     , h_path                    , up_left                   , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , ""        , ""                                  , ""                        , v_path                              , ""                        , ""                                    , ""                        , go_down([TextParams("11-12", boxed=True), " 4"]), ""                                            , ""                         , v_path("5")                   , ""                         , ""                        , ""            , ""                        , ""         , v_path                    , ""                                     , v_path                                            , ""                                              , v_path                                            , ""                        , ""            , ""                        , ""         , ""      , go_up                      , ""         , ""        , ""             , ""               , ""      , ""        ],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , base("B4"), go_left                             , h_path("2R")              , up_left                             , ""                        , ""                                    , ""                        , base("B5")                                      , ""                                            , ""                         , base("40")                    , h_path                     , base("41")                , h_path        , base("42")                , h_path("2"), up_left                   , ""                                     , v_path("6")                                       , ""                                              , v_path                                            , ""                        , ""            , ""                        , ""         , ""      , base("54")                 , go_left    , base("53"), go_left        , base("52")       , go_left , base("51")],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , v_path    , ""                                  , ""                        , ""                                  , ""                        , ""                                    , ""                        , v_path                                          , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , v_path                                            , ""                                              , go_down                                           , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , go_up     ],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , up_right  , h_path                              , h_path                    , go_right                            , color(P("D"), "#B2FF00"), ""                                    , ""                        , up_right                                        , h_path                                        , color(P("E"), "#FF0090") , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , base("45")                                        , h_path("5")                                     , base("46")                                        , h_path                    , h_path        , crossed_h_path            , h_path     , go_right, base("47")                 , go_right   , base("48"), go_right       , base("49")       , go_right, base("50")],
    [""            , ""  , ""                        , ""                        , ""                        , ""                                     , ""                                           , ""                                             , ""                        , ""                                         , ""                        , ""                        , ""                                             , ""                                             , ""                        , ""          , ""                        , ""    , ""                                  , ""     , ""                                            , ""        , ""                                  , ""                        , ""                                  , ""                        , ""                                    , ""                        , ""                                              , ""                                            , ""                         , ""                            , ""                         , ""                        , ""            , ""                        , ""         , ""                        , ""                                     , ""                                                , ""                                              , ""                                                , ""                        , ""            , ""                        , ""         , ""      , ""                         , ""         , ""        , ""             , ""               , ""      , ""        ],
]


# initial_map: list[list[Literal[""] | None | MapObjectInfo]] = [
#     [start("START"), None, None, None],
#     [None          , None, None, None],
#     [None          , None, None, None],
#     [None          , None, None, None],
# ]